title = "Diego Ceccarelli"
baseURL = "https://diegoceccarelli.github.io"
publishDir = "docs"
theme = "researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally
googleAnalytics = ""  # add your tracking id

[params]
  author = "Olivier Roques"
  description = "Diego Ceccarelli is software engineer and a team lead at Bloomberg in London, UK. His work is mainly on Information Retrieval, Search, and Machine Learning problems. "
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  [params.footer]
    text = "By Olivier Roques"
    url = "https://github.com/ojroques/hugo-researcher"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 1
  [[menu.main]]
    name = "Snippets"
    url = "/snippets"
    weight = 1

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
